---
apiVersion: v1
kind: Service
metadata:
  name: httpweb
  namespace: default
spec:
  selector:
    app: httpweb
  clusterIP: 
  type: NodePort
  ports:
  - port: 80
    targetPort: 8080
    nodePort: 30080
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: httpwebdeploy
  namespace: default
spec:
  replicas: 2
  selector:
    matchLabels:
      app: httpweb
  template:
    metadata:
      labels:
        app: httpweb
    spec:
      containers:
      - name: httpweb
        image: 192.168.2.4/devel/httpweb:v1.0
        imagePullPolicy: IfNotPresent
        ports:
        - name: http
          containerPort: 8080